# 切换环境
spring:
 profiles:
  active: dev
# 日志级别,默认就是info
#logging.level.org.apache.http=info
# log存放目录
logging:
 file:
  name: log/springboot.log

server:
 tomcat:
  accesslog:
   buffered: true
   enabled: true
   file-date-format: .yyyy-MM-dd
   pattern: '%h %l %u %t "%r" %s %b %D' 
   prefix: access_log
   rename-on-rotat: false
   request-attributes-enabled: false
   rotate: true
   suffix: .log 
   basedir: ./accesslog
#server.tomcat.accesslog.prefix=access_log 
#server.tomcat.accesslog.rename-on-rotate=false 
#server.tomcat.accesslog.request-attributes-enabled=false 
#server.tomcat.accesslog.rotate=true 
#server.tomcat.accesslog.suffix=.log 
#server.tomcat.basedir=./accesslog


#mybatis.configuration.log-prefix=mybatislog


